name: CI
on: [push, pull_request]
#  schedule:
#    - cron: '0 0-23/4 * * *'
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: arm64
            arch: arm64
            triplet: arm64-windows
            vcpkgPackages: 'benchmark'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
          vcpkgGitCommitId: d781bd9ca77ac3dc2f13d88169021d48459c665f
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
